/**
 * @jest-environment node
 */
// Cross-language Noise interoperability: the main-process initiator must
// reproduce byte-identical handshakes against vectors generated by the Go
// daemon (flynn/noise). Vectors are shared with the Chrome extension
// (extension/src/noise/testdata/vectors.json).
import { readFileSync } from 'fs';
import path from 'path';
import {
  CipherState,
  HandshakeError,
  XXHandshake,
  keyPairFromPrivate,
} from '../main/noise';

interface Vector {
  name: string;
  psk?: string;
  prologue: string;
  initStaticPriv: string;
  respStaticPub: string;
  initEphPriv: string;
  messages: string[];
  transportToResp: string;
  transportToInit: string;
  transportToRespPlain: string;
  transportToInitPlain: string;
}

const vectors: Vector[] = JSON.parse(
  readFileSync(path.join(__dirname, '../main/testdata/vectors.json'), 'utf8'),
);

const fromHex = (s: string): Uint8Array =>
  new Uint8Array((s.match(/.{2}/g) ?? []).map((b) => parseInt(b, 16)));
const toHex = (b: Uint8Array): string =>
  Array.from(b)
    .map((x) => x.toString(16).padStart(2, '0'))
    .join('');

function initiatorFor(v: Vector): XXHandshake {
  return new XXHandshake({
    staticKey: keyPairFromPrivate(fromHex(v.initStaticPriv)),
    psk: v.psk ? fromHex(v.psk) : undefined,
    prologue: fromHex(v.prologue),
    ephemeral: keyPairFromPrivate(fromHex(v.initEphPriv)),
  });
}

describe.each(vectors)('go interop: $name', (v) => {
  it('reproduces the Go handshake byte-for-byte', () => {
    const hs = initiatorFor(v);

    expect(toHex(hs.writeMessageA())).toBe(v.messages[0]);

    const payloadB = hs.readMessageB(fromHex(v.messages[1]!));
    expect(payloadB.length).toBe(0);
    expect(toHex(hs.remoteStatic)).toBe(v.respStaticPub);

    expect(toHex(hs.writeMessageC())).toBe(v.messages[2]);

    const { send, recv } = hs.split();
    const toResp = send.encryptWithAd(
      new Uint8Array(0),
      fromHex(v.transportToRespPlain),
    );
    expect(toHex(toResp)).toBe(v.transportToResp);
    const fromResp = recv.decryptWithAd(
      new Uint8Array(0),
      fromHex(v.transportToInit),
    );
    expect(toHex(fromResp)).toBe(v.transportToInitPlain);
  });

  it('rejects a tampered message 2', () => {
    const hs = initiatorFor(v);
    hs.writeMessageA();
    const bad = fromHex(v.messages[1]!);
    bad[40]! ^= 1;
    expect(() => hs.readMessageB(bad)).toThrow(HandshakeError);
  });

  it('rejects a tampered prologue (relay MITM)', () => {
    const prologue = fromHex(v.prologue);
    prologue[0]! ^= 1;
    const hs = new XXHandshake({
      staticKey: keyPairFromPrivate(fromHex(v.initStaticPriv)),
      psk: v.psk ? fromHex(v.psk) : undefined,
      prologue,
      ephemeral: keyPairFromPrivate(fromHex(v.initEphPriv)),
    });
    hs.writeMessageA();
    expect(() => hs.readMessageB(fromHex(v.messages[1]!))).toThrow(
      HandshakeError,
    );
  });
});

describe('CipherState', () => {
  it('rekeys deterministically at the interval and stays in sync', () => {
    const a = new CipherState();
    const b = new CipherState();
    const key = crypto.getRandomValues(new Uint8Array(32));
    a.initializeKey(key.slice());
    b.initializeKey(key.slice());
    const empty = new Uint8Array(0);
    const n = Number(CipherState.REKEY_INTERVAL) + 4;
    for (let i = 0; i < n; i += 1) {
      const ct = a.encryptWithAd(empty, new TextEncoder().encode(`m${i}`));
      const pt = b.decryptWithAd(empty, ct);
      expect(new TextDecoder().decode(pt)).toBe(`m${i}`);
    }
  });
});
