// Cross-language Noise interoperability tests: the TypeScript initiator must
// produce byte-identical handshakes against vectors generated by the Go
// daemon implementation (flynn/noise), plus negative and property tests.
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  CipherState,
  HandshakeError,
  XXHandshake,
  generateKeyPair,
  keyPairFromPrivate,
} from '../src/noise/noise'

interface Vector {
  name: string
  psk?: string
  prologue: string
  initStaticPriv: string
  respStaticPriv: string
  respStaticPub: string
  initEphPriv: string
  messages: string[]
  transportToResp: string
  transportToInit: string
  transportToRespPlain: string
  transportToInitPlain: string
}

const vectorsPath = fileURLToPath(new URL('../src/noise/testdata/vectors.json', import.meta.url))
const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, 'utf8'))

const fromHex = (s: string): Uint8Array =>
  new Uint8Array((s.match(/.{2}/g) ?? []).map((b) => parseInt(b, 16)))
const toHex = (b: Uint8Array): string =>
  Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('')

function initiatorFor(v: Vector): XXHandshake {
  return new XXHandshake({
    staticKey: keyPairFromPrivate(fromHex(v.initStaticPriv)),
    psk: v.psk ? fromHex(v.psk) : undefined,
    prologue: fromHex(v.prologue),
    ephemeral: keyPairFromPrivate(fromHex(v.initEphPriv)),
  })
}

describe.each(vectors)('go interop: $name', (v) => {
  it('reproduces the Go handshake byte-for-byte', () => {
    const hs = initiatorFor(v)

    const msg1 = hs.writeMessageA()
    expect(toHex(msg1)).toBe(v.messages[0])

    const payloadB = hs.readMessageB(fromHex(v.messages[1]!))
    expect(payloadB.length).toBe(0)
    expect(toHex(hs.remoteStatic)).toBe(v.respStaticPub)

    const msg3 = hs.writeMessageC()
    expect(toHex(msg3)).toBe(v.messages[2])

    const { send, recv } = hs.split()
    // Our transport encryption must equal Go's ciphertext…
    const toResp = send.encryptWithAd(new Uint8Array(0), fromHex(v.transportToRespPlain))
    expect(toHex(toResp)).toBe(v.transportToResp)
    // …and we must decrypt Go's responder traffic.
    const fromResp = recv.decryptWithAd(new Uint8Array(0), fromHex(v.transportToInit))
    expect(toHex(fromResp)).toBe(v.transportToInitPlain)
  })

  it('rejects a tampered message 2', () => {
    const hs = initiatorFor(v)
    hs.writeMessageA()
    const bad = fromHex(v.messages[1]!)
    bad[40]! ^= 1
    expect(() => hs.readMessageB(bad)).toThrow(HandshakeError)
  })

  it('rejects a truncated message 2', () => {
    const hs = initiatorFor(v)
    hs.writeMessageA()
    expect(() => hs.readMessageB(fromHex(v.messages[1]!).slice(0, 40))).toThrow(HandshakeError)
  })

  it('rejects a tampered prologue (relay MITM)', () => {
    const prologue = fromHex(v.prologue)
    prologue[0]! ^= 1
    const hs = new XXHandshake({
      staticKey: keyPairFromPrivate(fromHex(v.initStaticPriv)),
      psk: v.psk ? fromHex(v.psk) : undefined,
      prologue,
      ephemeral: keyPairFromPrivate(fromHex(v.initEphPriv)),
    })
    hs.writeMessageA()
    expect(() => hs.readMessageB(fromHex(v.messages[1]!))).toThrow(HandshakeError)
  })
})

describe('psk binding', () => {
  it('a wrong psk diverges from the transcript at message 3 and transport', () => {
    // With psk3 the PSK mixes into the chain only at message 3, so message 2
    // still reads; the divergence must show in message 3 bytes and in
    // transport keys (the daemon rejects message 3 — see Go-side tests).
    const v = vectors.find((x) => x.psk)!
    const hs = new XXHandshake({
      staticKey: keyPairFromPrivate(fromHex(v.initStaticPriv)),
      psk: new Uint8Array(32), // wrong
      prologue: fromHex(v.prologue),
      ephemeral: keyPairFromPrivate(fromHex(v.initEphPriv)),
    })
    hs.writeMessageA()
    hs.readMessageB(fromHex(v.messages[1]!))
    const msg3 = hs.writeMessageC()
    expect(toHex(msg3)).not.toBe(v.messages[2])
    const { recv } = hs.split()
    expect(() => recv.decryptWithAd(new Uint8Array(0), fromHex(v.transportToInit))).toThrow()
  })
})

describe('CipherState', () => {
  it('round-trips and detects tampering', () => {
    const cs1 = new CipherState()
    const cs2 = new CipherState()
    const key = crypto.getRandomValues(new Uint8Array(32))
    cs1.initializeKey(key.slice())
    cs2.initializeKey(key.slice())

    const ad = new TextEncoder().encode('ad')
    const ct = cs1.encryptWithAd(ad, new TextEncoder().encode('hello'))
    const pt = cs2.decryptWithAd(ad, ct)
    expect(new TextDecoder().decode(pt)).toBe('hello')

    const ct2 = cs1.encryptWithAd(ad, new TextEncoder().encode('again'))
    ct2[3]! ^= 1
    expect(() => cs2.decryptWithAd(ad, ct2)).toThrow()
  })

  it('rekeys deterministically at the interval and stays in sync', () => {
    const a = new CipherState()
    const b = new CipherState()
    const key = crypto.getRandomValues(new Uint8Array(32))
    a.initializeKey(key.slice())
    b.initializeKey(key.slice())
    const empty = new Uint8Array(0)
    const n = Number(CipherState.REKEY_INTERVAL) + 4
    for (let i = 0; i < n; i++) {
      const ct = a.encryptWithAd(empty, new TextEncoder().encode(`m${i}`))
      const pt = b.decryptWithAd(empty, ct)
      expect(new TextDecoder().decode(pt)).toBe(`m${i}`)
    }
  })
})

describe('handshake state machine', () => {
  it('enforces message order', () => {
    const hs = new XXHandshake({ staticKey: generateKeyPair(), prologue: new Uint8Array(0) })
    expect(() => hs.readMessageB(new Uint8Array(64))).toThrow(HandshakeError)
    expect(() => hs.writeMessageC()).toThrow(HandshakeError)
    expect(() => hs.remoteStatic).toThrow(HandshakeError)
  })

  it('generates distinct ephemeral keys', () => {
    const a = generateKeyPair()
    const b = generateKeyPair()
    expect(toHex(a.publicKey)).not.toBe(toHex(b.publicKey))
    expect(a.publicKey.length).toBe(32)
  })
})
